package ch.uzh.ifi.hase.soprafs23.constant;

public enum CardRank {
    ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, TEN, ELEVEN, TWELVE, THIRTEEN, ESCAPE, PIRATE, MERMAID, SCARY_MARY, SKULL_KING;
}
//BADEYE_JOE, BETTY_BRAVE, EVIL_EMMY, HARRY_THE_GIANT, TORTUGA_JACK